# Generated by Django 3.2.7 on 2021-11-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('D', 'Dance/Pop'), ('B', 'Ballad'), ('R', 'Rap')], default='D', max_length=1)),
                ('photocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.photocard')),
            ],
        ),
    ]
