# Generated by Django 3.2.7 on 2021-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_solo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='solo',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='solo',
            name='date',
            field=models.DateField(verbose_name='Release date'),
        ),
    ]
